
spring:
  # Spring Security ?????? SecurityProperties ???
  security:
    # ????? InMemoryUserDetailsManager ?????????
    user:
      name: user # ??
      password: user # ??
      roles: ADMIN # ????
server:
  port: 8989
