server:
  port: 8500

spring:
  #elasticsearch路径配置
  elasticsearch:
    uris: http://localhost:9200

#canal自定义配置
canal:
  host: "localhost"
  port: 11111
  destination: "example"
  has-sync-instance-to-es: false