spring:
  data:
    # MongoDB ?????? MongoProperties ?
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
#      username: test01
#      password: password01
      # ??????????? uri

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # ?? mongodb ????????????????????
server:
  port: 18080
