server:
  port: 8011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testsys?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=GMT%2b8&characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      #??????????
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #??hibernate????mysql?InnoDBD??,InnoDBD????
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #?????
        enable_lazy_load_no_trans: true


